name: Build and Deploy with Podman-Compose

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Ensure the runner has Podman installed or install it as part of the job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Podman
      run: |
        . /etc/os-release
        sudo sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$ID_$VERSION_ID/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
        sudo wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/$ID_$VERSION_ID/Release.key -O Release.key
        sudo apt-key add - < Release.key
        sudo apt-get update -qq
        sudo apt-get -qq -y install podman podman-docker

    - name: Run podman-compose build
      run: podman-compose build

    - name: Run podman-compose up
      run: podman-compose up -d

    - name: Cleanup
      if: always()
      run: podman-compose down
