version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "8081:8081"
    volumes:
      - ./frontend:/app
    command: npm run serve
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    command: flask run --host=0.0.0.0 --port=5001
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
